spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://buddybudd-db.cae195iepgm5.ap-northeast-2.rds.amazonaws.com:3306/buddybuddydb?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: tjalstn-9350
  jpa:
    database: mysql
    show-sql: true #hibernate가 실행한 모든 sql 출력
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: true
        format-sql: true #sql 문 beautify