spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://buddybudd-db.cae195iepgm5.ap-northeast-2.rds.amazonaws.com:3306/buddybuddydb?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    show-sql: true #hibernate가 실행한 모든 sql 출력
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect #geo 설정
    properties:
      hibernate:
        format-sql: true
  jwt:
    secret: ${JWT_KEY}
    token:
      access-expiration-time: 43200000    # 12시간
      refresh-expiration-time: 604800000   # 7일
  redis:
    host: localhost
    port: 6379

#Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.buddy.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    groups:
      enabled: true
    cache:
      disabled: true